### ISSUE TITLE
Reverse proxy access for Breeder Genomics Hub

### ISSUE THREAD

**Issue by chunhuaicheng** [maize-genetics/breeder-genomics-hub#3] opened 2024-11-12 18:29 UTC
Hi, 

I'm trying to set up reverse proxy for Breeder Genomics Hub. After some help described in [this issue](https://github.com/maize-genetics/breeder-genomics-hub/issues/2). I was able to get past the ORCID authentication. However, I got 404 error after that. Can someone help?

I have these settings in prod.env:

HUB_DOMAIN=http://192.168.122.89:80
REDIRECT_URI=https://hub.rosaceae.org/oauth/callback1

JupyterHub logs:

18:10:49.270 JupyterHub log:191] 302 GET / -> /hub/ (@172.18.0.3) 4.09ms
[I 2024-11-12 18:10:49.289 JupyterHub log:191] 302 GET /hub/ -> /hub/login?next=%2Fhub%2F (@172.18.0.3) 1.52ms
[I 2024-11-12 18:10:49.315 JupyterHub log:191] 200 GET /hub/login?next=%2Fhub%2F (@172.18.0.3) 9.12ms
[I 2024-11-12 18:10:51.366 JupyterHub oauth2:127] OAuth redirect: https://hub.rosaceae.org/oauth/callback1
[I 2024-11-12 18:10:51.370 JupyterHub log:191] 302 GET /hub/oauth_login?next=%2Fhub%2F -> https://orcid.org/oauth/authorize?response_type=code&redirect_uri=https%3A%2F%2Fhub.rosaceae.org%2Foauth%2Fcallback1&client_id=APP-UFWAMDKAJ84OW452&code_challenge=[secret]&code_challenge_method=[secret]&state=[secret]&scope=%2Fauthenticate+openid (@172.18.0.3) 4.49ms
[I 2024-11-12 18:11:24.906 JupyterHub log:191] 302 GET /oauth/callback1?code=[secret]&state=[secret] -> /hub/oauth/callback1?code=[secret]&state=[secret] (@172.18.0.3) 1.38ms
[W 2024-11-12 18:11:24.984 JupyterHub log:191] 404 GET /hub/oauth/callback1?code=[secret]&state=[secret] (@172.18.0.3) 3.17ms

**Comment by matthewwiese** [comment] 2024-11-13 17:09
@chunhuaicheng Hi, it's me again. Try setting your `REDIRECT_URI` to one of the following:
```
https://hub.rosaceae.org/oauth_callback
https://hub.rosaceae.org/hub/oauth_callback
```
I would use the second, but the first should work by redirecting to the second.

Based on the OAuthenticator [code here](https://github.com/jupyterhub/oauthenticator/blob/main/oauthenticator/oauth2.py) it expects the callback endpoint to be `/oauth_callback` and not `/oauth/callback1` so although authentication is successful you encounter the 404.

**Comment by chunhuaicheng** [comment] 2024-11-13 17:53
Thank you Matt. I've tried both 'REDIRECT_URI' and they both work. After I've logged in. I got an error saying:

500 : Internal Server Error
Unhandled error starting server 0009-0001-7454-927x
You can try restarting your server from the [home page](https://hub.rosaceae.org/hub/home).

Here's the logs:
[I 2024-11-13 17:49:12.699 JupyterHub log:191] 302 GET / -> /hub/ (@172.18.0.3) 2.13ms
[I 2024-11-13 17:49:12.768 JupyterHub log:191] 302 GET /hub/ -> /hub/spawn (0009-0001-7454-927x@172.18.0.3) 50.13ms
[I 2024-11-13 17:49:12.859 JupyterHub provider:659] Creating oauth client jupyterhub-user-0009-0001-7454-927x
[E 2024-11-13 17:49:12.929 JupyterHub user:884] Unhandled error starting 0009-0001-7454-927x's server: Error while fetching server API version: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/jupyterhub/user.py", line 798, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/usr/local/lib/python3.10/dist-packages/dockerspawner/dockerspawner.py", line 1294, in start
        await self.pull_image(image)
      File "/usr/local/lib/python3.10/dist-packages/dockerspawner/dockerspawner.py", line 1268, in pull_image
        await self.docker('inspect_image', image)
      File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/usr/local/lib/python3.10/dist-packages/dockerspawner/dockerspawner.py", line 992, in _docker
        m = getattr(self.client, method)
      File "/usr/local/lib/python3.10/dist-packages/dockerspawner/dockerspawner.py", line 140, in client
        client = docker.APIClient(**kwargs)
      File "/usr/local/lib/python3.10/dist-packages/docker/api/client.py", line 207, in __init__
        self._version = self._retrieve_server_version()
      File "/usr/local/lib/python3.10/dist-packages/docker/api/client.py", line 230, in _retrieve_server_version
        raise DockerException(
    docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

[E 2024-11-13 17:49:12.972 JupyterHub user:894] Failed to cleanup 0009-0001-7454-927x's server that failed to start
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/jupyterhub/user.py", line 892, in spawn
        await self.stop(spawner.name)
      File "/usr/local/lib/python3.10/dist-packages/jupyterhub/user.py", line 986, in stop
        status = await spawner.poll()
      File "/usr/local/lib/python3.10/dist-packages/dockerspawner/dockerspawner.py", line 1006, in poll
        container = await self.get_object()
      File "/usr/local/lib/python3.10/dist-packages/dockerspawner/dockerspawner.py", line 1029, in get_object
        obj = await self.docker("inspect_%s" % self.object_type, self.object_name)
      File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/usr/local/lib/python3.10/dist-packages/dockerspawner/dockerspawner.py", line 992, in _docker
        m = getattr(self.client, method)
      File "/usr/local/lib/python3.10/dist-packages/dockerspawner/dockerspawner.py", line 140, in client
        client = docker.APIClient(**kwargs)
      File "/usr/local/lib/python3.10/dist-packages/docker/api/client.py", line 207, in __init__
        self._version = self._retrieve_server_version()
      File "/usr/local/lib/python3.10/dist-packages/docker/api/client.py", line 230, in _retrieve_server_version
        raise DockerException(
    docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

[E 2024-11-13 17:49:12.975 JupyterHub pages:313] Error starting server 0009-0001-7454-927x: Error while fetching server API version: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))
    Traceback (most recent call last):
    NoneType: None

[W 2024-11-13 17:49:12.975 JupyterHub web:1869] 500 GET /hub/spawn (172.18.0.3): Unhandled error starting server 0009-0001-7454-927x
[E 2024-11-13 17:49:13.030 JupyterHub log:183] {
      "X-Forwarded-Port": "80",
      "X-Forwarded-Server": "hub.rosaceae.org",
      "X-Forwarded-Proto": "http,http",
      "X-Forwarded-Host": "192.168.122.89",
      "X-Forwarded-For": "192.168.122.1,172.18.0.3",
      "Upgrade-Insecure-Requests": "1",
      "Sec-Fetch-User": "?1",
      "Sec-Fetch-Site": "none",
      "Sec-Fetch-Mode": "navigate",
      "Sec-Fetch-Dest": "document",
      "Priority": "u=0, i",
      "Cookie": "_xsrf=[secret]; jupyterhub-hub-login=[secret]; jupyterhub-session-id=[secret]",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept-Encoding": "gzip, deflate, br, zstd",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0",
      "Host": "192.168.122.89",
      "Connection": "close"
    }
[E 2024-11-13 17:49:13.030 JupyterHub log:191] 500 GET /hub/spawn (0009-0001-7454-927x@172.18.0.3) 244.68ms

**Comment by matthewwiese** [comment] 2024-11-13 18:02
@chunhuaicheng Do a `docker pull maizegenetics/breeder-notebook:latest` to get the image that will be used for each client. It's pretty large, so times out the request. After you have it downloaded, you should be set.

I'm going to add this to the README because I've encountered it before myself and forgot to make a note.

**Comment by chunhuaicheng** [comment] 2024-11-13 18:29
I downloaded the image. However, I'm still getting the same error. It doesn't feel like a time out error though as it doesn't wait for a period of time. The 500 error showed immediately after I logged in. I've confirmed the image is now downloaded:

REPOSITORY                        TAG            IMAGE ID       CREATED         SIZE
breeder-genomics-hub-jupyterhub   latest         a28cdb7e5866   2 weeks ago     403MB
maizegenetics/breeder-notebook    latest         046cbe5955e1   13 months ago   9.19GB
caddy                             2.6.4-alpine   050db1833a9c   17 months ago   46MB

**Comment by matthewwiese** [comment] 2024-11-13 20:52
@chunhuaicheng Reading the logs more closely, it seems like the Docker Spawner can't access your Docker socket. I was able to reproduce your error with a non-existent socket.

Do you have a `docker.sock`? Run `ls /run/user/$(id -u)` - it should be in that directory.

If your socket is at `/var/run/docker.sock` then you're not running in [rootless mode](https://docs.docker.com/engine/security/rootless/). If you run Docker like `sudo docker` then that's the case.

I would advise against running Docker with root in this project, because it opens up a potential can of worms regarding the privileges of the spawned containers.

If you are running rootless Docker but still encountering the 500 error, please open a new issue. However, this may be a better question for the [DockerSpawner](https://github.com/jupyterhub/dockerspawner) folks because that's what is being used under the hood. I can do my best to point you in the right direction, at least.

I'm going to close this issue since we are off topic (again). 🙂

**Closed as completed** 2024-11-13 20:53 UTC
Labels: support

**Comment by lynnjo** [comment] 2024-11-14 11:39
@matthewwiese Thanks for jumping in and helping.  We appreciate your expertise in this area.
