### ISSUE TITLE
Allow HTTP access

### ISSUE THREAD

**Issue by chunhuaicheng** [maize-genetics/breeder-genomics-hub#2] opened 2024-11-07 17:24 UTC
Hi,

We don't usually expose our containers to the internet. Is it possible to allow HTTP access to the Breeder Genomics Hub container instead of HTTPS? We would like to set up reverse proxy and handle the SSL certificate ourselves.

The current container setup keeps failing and complains:

{"level":"error","ts":1730934791.3613434,"logger":"http.acme_client","msg":"challenge failed","identifier":"compute2.bioinfo.wsu.edu","challenge_type":"tls-alpn-01","problem":{"type":"urn:ietf:params:acme:error:connection","title":"","detail":"134.121.193.86: Timeout during connect (likely firewall problem)","instance":"","subproblems":[]}}
{"level":"error","ts":1730934791.3614395,"logger":"http.acme_client","msg":"validating authorization","identifier":"test.wsu.edu","problem":{"type":"urn:ietf:params:acme:error:connection","title":"","detail":"134.111.193.86: Timeout during connect (likely firewall problem)","instance":"","subproblems":[]},"order":"https://acme-v02.api.letsencrypt.org/acme/order/2042521267/320673611777","attempt":1,"max_attempts":3}

**Comment by matthewwiese** [comment] 2024-11-07 19:28
@chunhuaicheng Hi! Thanks for your interest in the project.

In order to force HTTP and not use Let's Encrypt for automatic HTTPS, all you have to do is modify the `prod.env` file like so:

```env
OAUTH_CLIENT_ID=<APP-123ABC>
OAUTH_CLIENT_SECRET=<ORCID Secret>
HUB_DOMAIN=http://0.0.0.0:80
```

By prefixing with `http://` Caddy will *not* utilize automatic HTTPS. If you want to listen on a different port, all you have to do is modify the [`hub.yml`](https://github.com/maize-genetics/breeder-genomics-hub/blob/main/hub.yml) Docker Compose file. Also, replace `0.0.0.0` with the IP address you wish to use on your LAN, or a domain name if supported by your local network's DNS.

I've updated the [Getting Started](https://hub.maizegenetics.net/getting-started) documentation to answer this question for future users. Let me know if you have any further questions! If not, I will close this issue.

Side note: If you run into the following error:
```
Error response from daemon: error while creating mount source path '/run/user/1001/docker.sock': mkdir /run/user/1001: permission denied
```
Git pull this repo to get the most recent version and follow the newly-added instructions on the Getting Starts docs I linked above. The Docker socket was previously hardcoded to expect the `1001` user.

**Comment by chunhuaicheng** [comment] 2024-11-07 22:16
Thank you for the prompt reply. I pulled from Git again and followed your instruction to change 'HUB_DOMAIN' to 'http://0.0.0.0:80'. I can now visit the site hosted in caddy. However, it only shows a blank page as shown in the picture:
![Screenshot 2024-11-07 130920](https://github.com/user-attachments/assets/796d8ca2-ceeb-41ec-8e1d-0f9fd1809ae2)

And advice?
Here's my caddy logs:
{"level":"info","ts":1731014152.6312659,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
{"level":"warn","ts":1731014152.6328557,"logger":"caddyfile","msg":"Site block has an unspecified IP address which only matches requests having that Host header; you probably want the 'bind' directive to configure the socket","address":"0.0.0.0"}
{"level":"warn","ts":1731014152.633647,"msg":"Caddyfile input is not formatted; run the 'caddy fmt' command to fix inconsistencies","adapter":"caddyfile","file":"/etc/caddy/Caddyfile","line":2}
{"level":"info","ts":1731014152.635266,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
{"level":"warn","ts":1731014152.6364026,"logger":"http","msg":"server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server","server_name":"srv0","http_port":80}
{"level":"info","ts":1731014152.6368194,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc000112d20"}
{"level":"info","ts":1731014152.637409,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/data/caddy"}
{"level":"info","ts":1731014152.6378727,"logger":"tls","msg":"finished cleaning storage units"}
{"level":"info","ts":1731014152.6377878,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
{"level":"info","ts":1731014152.640699,"msg":"autosaved config (load with --resume flag)","file":"/config/caddy/autosave.json"}

And jupyterhub logs:
[I 2024-11-07 21:15:54.433 JupyterHub app:2859] Running JupyterHub version 4.0.1
[I 2024-11-07 21:15:54.433 JupyterHub app:2889] Using Authenticator: oauthenticator.generic.GenericOAuthenticator-17.1.0
[I 2024-11-07 21:15:54.433 JupyterHub app:2889] Using Spawner: dockerspawner.dockerspawner.DockerSpawner-13.0.0
[I 2024-11-07 21:15:54.433 JupyterHub app:2889] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-4.0.1
[I 2024-11-07 21:15:54.452 JupyterHub app:1664] Loading cookie_secret from /srv/jupyterhub/jupyterhub_cookie_secret
[I 2024-11-07 21:15:54.558 JupyterHub proxy:556] Generating new CONFIGPROXY_AUTH_TOKEN
[I 2024-11-07 21:15:54.577 JupyterHub app:1984] Not using allowed_users. Any authenticated user will be allowed.
[I 2024-11-07 21:15:54.614 JupyterHub app:2928] Initialized 0 spawners in 0.004 seconds
[I 2024-11-07 21:15:54.623 JupyterHub metrics:278] Found 0 active users in the last ActiveUserPeriods.twenty_four_hours
[I 2024-11-07 21:15:54.625 JupyterHub metrics:278] Found 0 active users in the last ActiveUserPeriods.seven_days
[I 2024-11-07 21:15:54.628 JupyterHub metrics:278] Found 0 active users in the last ActiveUserPeriods.thirty_days
[W 2024-11-07 21:15:54.629 JupyterHub proxy:746] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2024-11-07 21:15:54.629 JupyterHub proxy:750] Starting proxy @ http://jupyterhub:8000/
21:15:55.040 [ConfigProxy] info: Proxying http://jupyterhub:8000 to (no default)
21:15:55.045 [ConfigProxy] info: Proxy API at http://127.0.0.1:8001/api/routes
21:15:55.546 [ConfigProxy] info: 200 GET /api/routes
[I 2024-11-07 21:15:55.547 JupyterHub app:3178] Hub API listening on http://jupyterhub:8081/hub/
21:15:55.550 [ConfigProxy] info: 200 GET /api/routes
[I 2024-11-07 21:15:55.550 JupyterHub proxy:477] Adding route for Hub: / => http://jupyterhub:8081
21:15:55.555 [ConfigProxy] info: Adding route / -> http://jupyterhub:8081
21:15:55.557 [ConfigProxy] info: Route added / -> http://jupyterhub:8081
21:15:55.558 [ConfigProxy] info: 201 POST /api/routes/
[I 2024-11-07 21:15:55.558 JupyterHub app:3245] JupyterHub is now running at http://jupyterhub:8000/
21:20:55.578 [ConfigProxy] info: 200 GET /api/routes
21:25:55.563 [ConfigProxy] info: 200 GET /api/routes
21:30:55.565 [ConfigProxy] info: 200 GET /api/routes
21:35:55.575 [ConfigProxy] info: 200 GET /api/routes

**Comment by matthewwiese** [comment] 2024-11-07 23:27
@chunhuaicheng Happy to help! This is my fault for not being more explicit that `0.0.0.0` isn't to be taken literally. I wrote:

> Also, replace 0.0.0.0 with the IP address you wish to use on your LAN, or a domain name if supported by your local network's DNS.

You *don't* want to use `0.0.0.0` because that's what Caddy uses as the site address, i.e. it matches the request it receives to this host. So you're greeted with a blank `200` status page because the connection succeeded, but your IP `192.168.122.89` did not match `0.0.0.0`, and thus is not sent along to JupyterHub.

Use your IP address instead and it should work:

```
HUB_DOMAIN=http://192.168.122.89:80
```

**Comment by chunhuaicheng** [comment] 2024-11-07 23:53
Great Thanks! Feels like I'm one step closer but I got another problem about the Redirect URI:
![Screenshot 2024-11-07 154608](https://github.com/user-attachments/assets/d8b78b7c-ebf6-451e-8de0-a2307fea25be)

Is there a setting in prod.env that I can use to set Redirect URI instead of using the 'HUB_DOMAIN'? This way I can use our real domain name which is a reverse proxy server.

**Comment by matthewwiese** [comment] 2024-11-08 00:15
@chunhuaicheng I've added a `REDIRECT_URI` value that can be included in the environment file:
```
REDIRECT_URI=https://thirdparty.com/oauth/callback1
```

**Comment by chunhuaicheng** [comment] 2024-11-08 00:44
It works! I got past the authentication. But now I have a 404 error.
<img width="646" alt="Screenshot 2024-11-07 163757" src="https://github.com/user-attachments/assets/e0345f9e-11f1-4247-8a8a-3c8ad13afd7c">

**Comment by matthewwiese** [comment] 2024-11-08 01:52
@chunhuaicheng I'm going to close this issue as resolved since we are now off topic.

Regarding the 404, please open a new issue and post your logs. Additionally, try adding a redirect URI that uses the IP address you gave me instead of the reverse proxy to better narrow down the cause. If you continue to have problems somebody in the lab can help you (I no longer work there).

**Closed as completed by matthewwiese** 2024-11-08 01:52 UTC
Labels: support
